version: '3.3'
services:
  db:
    image: postgres:13.14
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - db:/var/lib/postgresql/data
volumes:
  db: